//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prajwal_GIF_Demo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentClass
    {
        public int Id { get; set; }
        public string StudentId { get; set; }
        public string ClassId { get; set; }
    }
}
